-- MySQL Script generated by MySQL Workbench
-- Wed May 16 15:24:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Balise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Balise` (
  `id_balise` INT NOT NULL AUTO_INCREMENT,
  `libellé` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_balise`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Contact` (
  `id_contact` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `con_nom` VARCHAR(255) NOT NULL,
  `con_prenom` VARCHAR(255) NOT NULL,
  `con_mail` VARCHAR(255) NOT NULL,
  `con_niveau` VARCHAR(255) NULL,
  `con_newsletter` TINYINT NOT NULL,
  `con_question` MEDIUMTEXT NOT NULL,
  `id_balise` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_contact`),
  INDEX `id_balise_idx` (`id_balise` ASC),
  CONSTRAINT `id_balise`
    FOREIGN KEY (`id_balise`)
    REFERENCES `Balise` (`id_balise`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
